# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0002_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='data_sources.datasource'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'ingestion_job'], name='ingestion_r_organiz_eaa135_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['organization', 'status'], name='ingestion_i_organiz_3b96f1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['organization', 'created_at'], name='ingestion_i_organiz_610b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['data_source', 'status'], name='ingestion_i_data_so_28c24b_idx'),
        ),
    ]
