services:
  - type: web
    name: breathe-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn breathe.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: breathe.settings
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: ALLOWED_HOSTS
        value: '*.onrender.com'
      - key: CORS_ALLOWED_ORIGINS
        value: 'https://breathe-frontend.onrender.com'
    regions:
      - oregon

  - type: web
    name: breathe-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: 'https://breathe-backend.onrender.com/api'
    regions:
      - oregon

databases:
  - name: postgres
    plan: starter
    ipAllowList:
      - key: render
        value: 0.0.0.0/0
