# Generated by Django 4.2.11 on 2026-05-29 04:51

from django.db import migrations
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', organizations.models.UserManager()),
            ],
        ),
    ]
