# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('outlier', 'Statistical Outlier'), ('missing_field', 'Missing Required Field'), ('duplicate', 'Potential Duplicate'), ('invalid_format', 'Invalid Format'), ('suspicious_value', 'Suspicious Value')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=100)),
                ('threshold_value', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('analyst_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emissions_anomaly_flag',
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending_review', max_length=20)),
                ('emission_category', models.CharField(choices=[('scope_1_fuel', 'Scope 1 - Fuel Combustion'), ('scope_1_process', 'Scope 1 - Process Emissions'), ('scope_2_electricity', 'Scope 2 - Electricity'), ('scope_2_steam', 'Scope 2 - Steam/Heat'), ('scope_3_travel', 'Scope 3 - Travel'), ('scope_3_procurement', 'Scope 3 - Procurement'), ('scope_3_waste', 'Scope 3 - Waste')], max_length=50)),
                ('emission_source', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('emissions_kg_co2e', models.DecimalField(decimal_places=4, max_digits=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_reference_id', models.CharField(blank=True, max_length=255)),
                ('asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_value', models.JSONField()),
                ('edited_value', models.JSONField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('review_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='data_sources.datasource')),
            ],
            options={
                'db_table': 'emissions_normalized_record',
            },
        ),
    ]
