# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='ingestion_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.ingestionjob'),
        ),
    ]
