# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0001_initial'),
        ('emissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_record', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='normalized_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='emissions.normalizedemissionrecord'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'status'], name='emissions_n_organiz_958d07_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'emission_category'], name='emissions_n_organiz_6130fc_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='emissions_n_organiz_8ff67b_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['ingestion_job', 'status'], name='emissions_n_ingesti_262595_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['facility_code', 'period_start'], name='emissions_n_facilit_a6c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['organization', 'severity'], name='emissions_a_organiz_5bbefd_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['normalized_record', 'is_resolved'], name='emissions_a_normali_a22c05_idx'),
        ),
    ]
