# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('sap_csv', 'SAP CSV Export'), ('utility_csv', 'Utility Portal CSV'), ('travel_api', 'Travel Expense API')], max_length=50)),
                ('connection_config', models.JSONField(blank=True, default=dict)),
                ('field_mappings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_sources_datasource',
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_unit', models.CharField(max_length=50)),
                ('target_unit', models.CharField(default='kg_co2e', max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('factor_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_sources_emission_factor',
            },
        ),
    ]
