# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['organization', 'factor_type', 'effective_from'], name='data_source_organiz_25538a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('organization', 'source_unit', 'factor_type', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'source_type'], name='data_source_organiz_f4c26b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('organization', 'name')},
        ),
    ]
