# Generated by Django 4.2.11 on 2026-05-26 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField()),
                ('record_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('comment_added', 'Comment Added')], max_length=50)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_audit_log',
            },
        ),
    ]
